package languagelab.lang.textual;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.TemplateModuleBase;
import jetbrains.mps.generator.runtime.TemplateModel;
import jetbrains.mps.smodel.language.LanguageRegistry;
import jetbrains.mps.smodel.language.LanguageRuntime;
import java.util.Collection;
import main.TemplateModelImpl;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import org.jetbrains.mps.openapi.language.SLanguage;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Generator extends TemplateModuleBase {
  private TemplateModel[] models;

  public Generator(LanguageRegistry languageRegistry, LanguageRuntime sourceLanguage) {
    super(languageRegistry, sourceLanguage);
  }
  @Override
  public String getAlias() {
    return "languagelab.lang.textual/main";
  }

  @Override
  public Collection<TemplateModel> getModels() {
    if (models == null) {
      models = new TemplateModel[1];
      models[0] = new TemplateModelImpl(this);
    }
    return Arrays.asList(models);
  }


  @NotNull
  @Override
  public SModuleReference getModuleReference() {
    return PersistenceFacade.getInstance().createModuleReference("cbbf54cc-c1b2-4507-9992-1cea17958418(languagelab.lang.textual#01)");
  }

  @Override
  public Collection<SLanguage> getTargetLanguages() {
    SLanguage[] rv = new SLanguage[4];
    rv[0] = MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    rv[1] = MetaAdapterFactory.getLanguage(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, "jetbrains.mps.lang.editor");
    rv[2] = MetaAdapterFactory.getLanguage(0xb401a68083254110L, 0x8fd384331ff25befL, "jetbrains.mps.lang.generator");
    rv[3] = MetaAdapterFactory.getLanguage(0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, "languagelab.mps.lang.adaptedGenerator");
    return Arrays.asList(rv);
  }

}
