package languagelab.lang.smodel.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ChildRef_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new PropertyRef_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new ReferenceRef_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x1111b0d61b274daaL, 0x92f98b9e03529a60L, 0x4f31c8d37d2477eeL), MetaIdFactory.conceptId(0x1111b0d61b274daaL, 0x92f98b9e03529a60L, 0x4fdf930a19049c8fL), MetaIdFactory.conceptId(0x1111b0d61b274daaL, 0x92f98b9e03529a60L, 0x4f31c8d37d2477ebL)).seal();
}
