package main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.MapConfigBase;
import jetbrains.mps.generator.runtime.TemplateMappingConfiguration;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateReductionRule;
import jetbrains.mps.generator.runtime.TemplateRootMappingRule;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateModel;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.runtime.ReductionRuleBase;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.GenerationException;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.generator.runtime.MapRootRuleBase;

@Generated
public class Mapping_main extends MapConfigBase implements TemplateMappingConfiguration {
  private final Collection<TemplateReductionRule> rules;
  private final Collection<TemplateRootMappingRule> rootRules;
  public Mapping_main(@NotNull TemplateModel model) {
    super(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "6026281361579188407"), "main", model, false);
    rules = TemplateUtil.<TemplateReductionRule>asCollection(new Mapping_main.ReductionRule0(), new Mapping_main.ReductionRule1(), new Mapping_main.ReductionRule2(), new Mapping_main.ReductionRule3());
    rootRules = TemplateUtil.<TemplateRootMappingRule>asCollection(new Mapping_main.RootMappingRule0());
  }
  @Override
  public Collection<TemplateReductionRule> getReductionRules() {
    return rules;
  }
  @Override
  public Collection<TemplateRootMappingRule> getRootRules() {
    return rootRules;
  }
  /*package*/ static final class ReductionRule0 extends ReductionRuleBase {
    public ReductionRule0() {
      super(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "5751329688189757027"), MetaAdapterFactory.getConcept(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb6fL, "languagelab.lang.textual.structure.TextAggregate"), false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = new Template_reduce_TextAggregate().apply(environment, context);
      return tlist1;
    }
  }
  /*package*/ static final class ReductionRule1 extends ReductionRuleBase {
    public ReductionRule1() {
      super(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "5751329688189757067"), MetaAdapterFactory.getConcept(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb73L, "languagelab.lang.textual.structure.TextConstant"), false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = new Template_reduce_TextConstant().apply(environment, context);
      return tlist1;
    }
  }
  /*package*/ static final class ReductionRule2 extends ReductionRuleBase {
    public ReductionRule2() {
      super(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "485512855557967897"), MetaAdapterFactory.getConcept(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb71L, "languagelab.lang.textual.structure.TextAttribute"), false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = null;
      if (QueriesGenerated.rule_Condition_1_0(new BaseMappingRuleContext(context, rule_ief6mt_b0a0c0b7))) {
        Collection<SNode> tlist2 = new Template_reduce_TextProperty_Name().apply(environment, context);
        tlist1 = tlist2;
      } else {
        Collection<SNode> tlist3 = new Template_reduce_TextProperty().apply(environment, context);
        tlist1 = tlist3;
      }
      return tlist1;
    }
  }
  /*package*/ static final class ReductionRule3 extends ReductionRuleBase {
    public ReductionRule3() {
      super(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "485512855558236042"), MetaAdapterFactory.getConcept(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb6cL, "languagelab.lang.textual.structure.TextReference"), false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = null;
      if (QueriesGenerated.rule_Condition_1_1(new BaseMappingRuleContext(context, rule_ief6mt_b0a0c0b8))) {
        Collection<SNode> tlist2 = new Template_reduce_TextReference_Name().apply(environment, context);
        tlist1 = tlist2;
      } else {
        Collection<SNode> tlist3 = new Template_reduce_TextReference().apply(environment, context);
        tlist1 = tlist3;
      }
      return tlist1;
    }
  }
  /*package*/ static final class RootMappingRule0 extends MapRootRuleBase implements TemplateRootMappingRule {
    public RootMappingRule0() {
      super(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "8714292893671308282"), MetaAdapterFactory.getConcept(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x6d0f56d69c3c1cbaL, "languagelab.lang.textual.structure.TextSyntax"), false, false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> result = new Template_INamedConcept_Editor().apply(environment, context);
      environment.registerLabel(context.getInput(), result, "autoGeneratedLabel");
      return result;
    }
  }
  private static SNodePointer rule_ief6mt_b0a0c0b7 = new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "485512855557967897");
  private static SNodePointer rule_ief6mt_b0a0c0b8 = new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "485512855558236042");
}
