package main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public static boolean rule_Condition_1_0(final BaseMappingRuleContext _context) {
    return _context.getNode().getReferenceTarget("attr") == SNodeOperations.getNode("r:c96e4637-75c9-4b73-89bf-641fdfcc1904(languagelab.lang.structure.predefined)", "4342015758195050749");
  }
  public static boolean rule_Condition_1_1(final BaseMappingRuleContext _context) {
    return _context.getNode().getReferenceTarget("attr") == SNodeOperations.getNode("r:c96e4637-75c9-4b73-89bf-641fdfcc1904(languagelab.lang.structure.predefined)", "4342015758195050749");
  }
  public static Object propertyMacro_GetValue_6_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb73L, 0x4fd0d3e12aafcb75L, "text"));
  }
  public static Object referenceMacro_GetReferent_2_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x6d0f56d69c3c1cbaL, 0x55ce2ad3d281e42bL, "type")), "autoGeneratedLabel");
  }
  public static Object referenceMacro_GetReferent_3_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb71L, 0x4fd0d3e12aafcb72L, "attr")), "autoGeneratedLabel");
  }
  public static Object referenceMacro_GetReferent_4_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb6fL, 0x4fd0d3e12aafcb70L, "aggr")), "autoGeneratedLabel");
  }
  public static Object referenceMacro_GetReferent_5_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb6cL, 0x4fd0d3e12ab5ad1cL, "attr")), "autoGeneratedLabel");
  }
  public static Object referenceMacro_GetReferent_5_1(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb6cL, 0x4fd0d3e12aafcb6dL, "refe")), "autoGeneratedLabel");
  }
  public static Object referenceMacro_GetReferent_8_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb6cL, 0x4fd0d3e12aafcb6dL, "refe")), "autoGeneratedLabel");
  }
  public static Iterable<SNode> sourceNodesQuery_2_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x6d0f56d69c3c1cbaL, 0x1978f0365912249L, "symbols"));
  }
}
