package main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.TemplateModelBase;
import jetbrains.mps.generator.runtime.TemplateModel2;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateMappingConfiguration;
import jetbrains.mps.generator.runtime.TemplateSwitchMapping;
import org.jetbrains.mps.openapi.model.SModelReference;
import jetbrains.mps.generator.runtime.TemplateModule;
import jetbrains.mps.generator.runtime.TemplateUtil;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.generator.runtime.TemplateDeclaration;
import jetbrains.mps.generator.runtime.TemplateDeclarationKey;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;

@Generated
public class TemplateModelImpl extends TemplateModelBase implements TemplateModel2 {
  private final Collection<TemplateMappingConfiguration> mappings;
  private final Collection<TemplateSwitchMapping> switches;
  private final SModelReference model;
  public TemplateModelImpl(TemplateModule module) {
    super(module);
    mappings = TemplateUtil.<TemplateMappingConfiguration>asCollection(new Mapping_main(this));
    switches = TemplateUtil.<TemplateSwitchMapping>asCollection();
    model = PersistenceFacade.getInstance().createModelReference("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)");
  }
  public String getLongName() {
    return "main";
  }
  public SModelReference getSModelReference() {
    return model;
  }
  public Collection<TemplateMappingConfiguration> getConfigurations() {
    return mappings;
  }
  public Collection<TemplateSwitchMapping> getSwitches() {
    return switches;
  }

  @Nullable
  @Override
  public TemplateDeclaration loadTemplate(TemplateDeclarationKey key) {
    if (!(model.equals(key.getSourceModel()))) {
      return null;
    }
    final SNodeReference template = key.getSourceNode();
    if (template.equals(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "5751329688189757017"))) {
      return new Template_reduce_TextProperty();
    }
    if (template.equals(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "5751329688189757035"))) {
      return new Template_reduce_TextAggregate();
    }
    if (template.equals(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "5751329688189757049"))) {
      return new Template_reduce_TextReference();
    }
    if (template.equals(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "5751329688189757075"))) {
      return new Template_reduce_TextConstant();
    }
    if (template.equals(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "485512855557934262"))) {
      return new Template_reduce_TextProperty_Name();
    }
    if (template.equals(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "485512855558239752"))) {
      return new Template_reduce_TextReference_Name();
    }
    if (template.equals(new SNodePointer("r:8f686c14-57a1-42ec-b78f-dc89d09136f4(main@generator)", "5751329688189737631"))) {
      return new Template_INamedConcept_Editor();
    }
    return null;
  }
}
