package languagelab.lang.structure.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_AttrType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AttrType() {
    super(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x3c41f053bc608d97L, "AttrType", "r:862bdb7b-f55f-49a6-bc53-62cd4f9465cc(languagelab.lang.structure.structure)/4342015758195264919", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_llString_0 = new EnumerationDescriptor.MemberDescriptor("llString", "llString", "r:862bdb7b-f55f-49a6-bc53-62cd4f9465cc(languagelab.lang.structure.structure)/4342015758195264920", "llString");
  private final EnumerationDescriptor.MemberDescriptor VALUE_llInt_0 = new EnumerationDescriptor.MemberDescriptor("llInt", "llInt", "r:862bdb7b-f55f-49a6-bc53-62cd4f9465cc(languagelab.lang.structure.structure)/4342015758195264921", "llInt");
  private final EnumerationDescriptor.MemberDescriptor VALUE_llBoolean_0 = new EnumerationDescriptor.MemberDescriptor("llBoolean", "llBoolean", "r:862bdb7b-f55f-49a6-bc53-62cd4f9465cc(languagelab.lang.structure.structure)/4342015758195264924", "llBoolean");
  private final EnumerationDescriptor.MemberDescriptor VALUE_llEnum_0 = new EnumerationDescriptor.MemberDescriptor("llEnum", "llEnum", "r:862bdb7b-f55f-49a6-bc53-62cd4f9465cc(languagelab.lang.structure.structure)/4342015758195264928", "llEnum");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_llString_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_llString_0, VALUE_llInt_0, VALUE_llBoolean_0, VALUE_llEnum_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "llString":
        return VALUE_llString_0;
      case "llInt":
        return VALUE_llInt_0;
      case "llBoolean":
        return VALUE_llBoolean_0;
      case "llEnum":
        return VALUE_llEnum_0;
    }
    return null;
  }
}
