package languagelab.lang.structure.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Aggregate_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Attribute_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new EnumElement_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Enumeration_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Reference_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Type_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1d49f38c2913f9d3L), MetaIdFactory.conceptId(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1978f03659121e6L), MetaIdFactory.conceptId(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1678091ddc6fa498L), MetaIdFactory.conceptId(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x3f880d78dc146632L), MetaIdFactory.conceptId(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1978f03659088ddL), MetaIdFactory.conceptId(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL)).seal();
}
