package languagelab.lang.structure.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.MapConfigBase;
import jetbrains.mps.generator.runtime.TemplateMappingConfiguration;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateReductionRule;
import jetbrains.mps.generator.runtime.TemplateRootMappingRule;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateModel;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.runtime.ReductionRuleBase;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.GenerationException;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import jetbrains.mps.generator.runtime.MapRootRuleBase;

@Generated
public class Mapping_main extends MapConfigBase implements TemplateMappingConfiguration {
  private final Collection<TemplateReductionRule> rules;
  private final Collection<TemplateRootMappingRule> rootRules;
  public Mapping_main(@NotNull TemplateModel model) {
    super(new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "114717560272881752"), "main", model, false);
    rules = TemplateUtil.<TemplateReductionRule>asCollection(new Mapping_main.ReductionRule0(), new Mapping_main.ReductionRule1(), new Mapping_main.ReductionRule2(), new Mapping_main.ReductionRule3());
    rootRules = TemplateUtil.<TemplateRootMappingRule>asCollection(new Mapping_main.RootMappingRule0(), new Mapping_main.RootMappingRule1());
  }
  @Override
  public Collection<TemplateReductionRule> getReductionRules() {
    return rules;
  }
  @Override
  public Collection<TemplateRootMappingRule> getRootRules() {
    return rootRules;
  }
  /*package*/ static final class ReductionRule0 extends ReductionRuleBase {
    public ReductionRule0() {
      super(new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167315391"), MetaAdapterFactory.getConcept(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1978f03659121e6L, "languagelab.lang.structure.structure.Attribute"), false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = new Template_llreduce_Attribute().apply(environment, context);
      environment.registerLabel(context.getInput(), tlist1, "autoGeneratedLabel");
      return tlist1;
    }
  }
  /*package*/ static final class ReductionRule1 extends ReductionRuleBase {
    public ReductionRule1() {
      super(new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167315396"), MetaAdapterFactory.getConcept(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1978f03659088ddL, "languagelab.lang.structure.structure.Reference"), false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = new Template_llreduce_Reference().apply(environment, context);
      environment.registerLabel(context.getInput(), tlist1, "autoGeneratedLabel");
      return tlist1;
    }
  }
  /*package*/ static final class ReductionRule2 extends ReductionRuleBase {
    public ReductionRule2() {
      super(new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167315399"), MetaAdapterFactory.getConcept(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1d49f38c2913f9d3L, "languagelab.lang.structure.structure.Aggregate"), false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = new Template_llreduce_Aggregate().apply(environment, context);
      environment.registerLabel(context.getInput(), tlist1, "autoGeneratedLabel");
      return tlist1;
    }
  }
  /*package*/ static final class ReductionRule3 extends ReductionRuleBase {
    public ReductionRule3() {
      super(new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167315403"), MetaAdapterFactory.getConcept(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1678091ddc6fa498L, "languagelab.lang.structure.structure.EnumElement"), false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = new Template_llreduce_EnumElement().apply(environment, context);
      environment.registerLabel(context.getInput(), tlist1, "autoGeneratedLabel");
      return tlist1;
    }
  }
  /*package*/ static final class RootMappingRule0 extends MapRootRuleBase implements TemplateRootMappingRule {
    public RootMappingRule0() {
      super(new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "8714292893671308282"), MetaAdapterFactory.getConcept(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, "languagelab.lang.structure.structure.Type"), false, false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> result = new Template_llmap_Type().apply(environment, context);
      environment.registerLabel(context.getInput(), result, "autoGeneratedLabel");
      return result;
    }
  }
  /*package*/ static final class RootMappingRule1 extends MapRootRuleBase implements TemplateRootMappingRule {
    public RootMappingRule1() {
      super(new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167311804"), MetaAdapterFactory.getConcept(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x3f880d78dc146632L, "languagelab.lang.structure.structure.Enumeration"), false, false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> result = new Template_llmap_Enumeration().apply(environment, context);
      environment.registerLabel(context.getInput(), result, "autoGeneratedLabel");
      return result;
    }
  }
}
