package languagelab.lang.structure.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.smodel.SNodeId;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.module.SModuleId;
import jetbrains.mps.project.ModuleId;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import languagelab.lang.structure.utils.SStuffHelper;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPointerOperations;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import java.util.Objects;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetValue_0_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetValue_0_1(final PropertyMacroContext _context) {
    return String.valueOf(((SNodeId.Regular) _context.getNode().getNodeId()).getId());
  }
  public static Object propertyMacro_GetValue_1_0(final PropertyMacroContext _context) {
    return String.valueOf(((SNodeId.Regular) _context.getNode().getNodeId()).getId());
  }
  public static Object propertyMacro_GetValue_1_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetValue_2_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetValue_2_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetValue_3_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetValue_3_1(final PropertyMacroContext _context) {
    return String.valueOf(((SNodeId.Regular) _context.getNode().getNodeId()).getId());
  }
  public static Object propertyMacro_GetValue_5_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetValue_6_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, 0x27b70365d7759284L, "rootable"));
  }
  public static Object propertyMacro_GetValue_6_1(final PropertyMacroContext _context) {
    return String.valueOf(((SNodeId.Regular) _context.getNode().getNodeId()).getId());
  }
  public static Object propertyMacro_GetValue_6_2(final PropertyMacroContext _context) {
    SNode originalNode = _context.getOriginalCopiedInputNode(_context.getNode());
    SModuleId moduleId = originalNode.getModel().getModule().getModuleId();
    return ((ModuleId.Regular) moduleId).getUUID().toString();
  }
  public static Object propertyMacro_GetValue_6_3(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_0_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1d49f38c2913f9d3L, 0x1d49f38c29140d0dL, "type")), "autoGeneratedLabel");
  }
  public static Object referenceMacro_GetReferent_1_0(final ReferenceMacroContext _context) {
    String attributeType = _context.getNode().getProperty(SStuffHelper.ATTRIBUTE_TYPE);
    if ("llString".equals(attributeType) || (attributeType == null || attributeType.length() == 0)) {
      // llString is default enum value, so it might be attributeType==null 
      return SPointerOperations.resolveNode(new SNodePointer("r:00000000-0000-4000-0000-011c89590288(jetbrains.mps.lang.core.structure)", "1082983041843"), _context.getOriginalInputModel().getRepository());
    }
    if ("llInt".equals(attributeType)) {
      return SPointerOperations.resolveNode(new SNodePointer("r:00000000-0000-4000-0000-011c89590288(jetbrains.mps.lang.core.structure)", "1082983657062"), _context.getOriginalInputModel().getRepository());
    }
    if ("llBoolean".equals(attributeType)) {
      return SPointerOperations.resolveNode(new SNodePointer("r:00000000-0000-4000-0000-011c89590288(jetbrains.mps.lang.core.structure)", "1082983657063"), _context.getOriginalInputModel().getRepository());
    }
    if ("llEnum".equals(attributeType)) {
      SNode enumDecl = _context.getNode().getReferenceTarget(SStuffHelper.ATTRIBUTE_ENUMTYPE);
      return (SNode) (_context.getOutputNodeByInputNodeAndMappingLabel(enumDecl, "enum"));
    }
    _context.showWarningMessage(_context.getNode(), "LL - Unknown AttrType: " + attributeType);
    return SPointerOperations.resolveNode(new SNodePointer("r:00000000-0000-4000-0000-011c89590288(jetbrains.mps.lang.core.structure)", "1082983041843"), _context.getOriginalInputModel().getRepository());
  }
  public static Object referenceMacro_GetReferent_3_0(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1978f03659088ddL, 0x1978f03659088f7L, "type")), "autoGeneratedLabel");
  }
  public static Object referenceMacro_GetReferent_6_0(final ReferenceMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, 0x55ce2ad3d281e42bL, "parentType")) != null) {
      return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, 0x55ce2ad3d281e42bL, "parentType"));
    }
    // this is not completely correct - just a trick for now 
    return SPointerOperations.resolveNode(new SNodePointer("r:00000000-0000-4000-0000-011c89590288(jetbrains.mps.lang.core.structure)", "1133920641626"), null);
  }
  public static Object referenceMacro_GetReferent_6_1(final ReferenceMacroContext _context) {
    return ListSequence.fromList(SModelOperations.roots(_context.getOriginalInputModel(), MetaAdapterFactory.getInterfaceConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, "jetbrains.mps.lang.core.structure.INamedConcept"))).where(new _FunctionTypes._return_P1_E0<Boolean, SNode>() {
      public Boolean invoke(SNode it) {
        return Objects.equals(SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")), SPropertyOperations.getString(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getInterfaceConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, "jetbrains.mps.lang.core.structure.INamedConcept")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
      }
    }).first();
  }
  public static boolean ifMacro_Condition_6_0(final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, 0x1d49f38c290821baL, "isNamed"));
  }
  public static boolean ifMacro_Condition_6_1(final IfMacroContext _context) {
    if (!(SModelOperations.getModelName(SNodeOperations.getModel(_context.getNode())).startsWith("languagelab.lang"))) {
      return false;
    }
    if (SModelOperations.getModelName(SNodeOperations.getModel(_context.getNode())).endsWith("structure.structure")) {
      return false;
    }
    for (SNode chld : ListSequence.fromList(SNodeOperations.getChildren(_context.getNode()))) {
      if (SNodeOperations.getConcept(chld).getName().equals("Reference")) {
        if (SPropertyOperations.getString(SNodeOperations.cast(ListSequence.fromList(SNodeOperations.getReferences(chld)).first().getTargetNode(), MetaAdapterFactory.getInterfaceConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, "jetbrains.mps.lang.core.structure.INamedConcept")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Type")) {
          return true;
        }
      }
    }
    return false;
  }
  public static Iterable<SNode> sourceNodesQuery_5_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x3f880d78dc146632L, 0x3f880d78dc14f462L, "elements"));
  }
  public static Iterable<SNode> sourceNodesQuery_6_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, 0x1978f03659088e1L, "references"));
  }
  public static Iterable<SNode> sourceNodesQuery_6_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, 0x1d49f38c291302ceL, "aggregates"));
  }
  public static Iterable<SNode> sourceNodesQuery_6_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, 0x1978f0365912249L, "attributes"));
  }
}
