package languagelab.lang.structure.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.TemplateDeclarationBase;
import jetbrains.mps.generator.runtime.TemplateDeclaration;
import org.jetbrains.mps.openapi.model.SNodeReference;
import java.util.Collection;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.GenerationException;
import org.jetbrains.mps.openapi.model.SNodeAccessUtil;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.smodel.SReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.SNodePointer;

@Generated
public class Template_llmap_Enumeration extends TemplateDeclarationBase implements TemplateDeclaration {

  public Template_llmap_Enumeration() {
  }

  public SNodeReference getTemplateNode() {
    return template_2hqiun_a0a3;
  }
  public Collection<SNode> apply(@NotNull final TemplateExecutionEnvironment environment, @NotNull final TemplateContext context) throws GenerationException {
    Collection<SNode> tlist1 = null;
    TemplateContext context1 = context.subContext("enum");
    final SNode tnode2 = environment.createOutputNode(myConcepts[0]);
    try {
      environment.nodeCopied(context1, tnode2, "tpl/r:858292f3-d079-42c7-a340-20af00941ea2/5333329965167315375");
      SNodeAccessUtil.setProperty(tnode2, myProperties[0], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetValue_5_0(new PropertyMacroContext(context1, "llmap_Enumeration", propertyMacro_2hqiun_c0a0c0b0d0e))));
      tnode2.setReference(myAssociationLinks[0], SReference.create(myAssociationLinks[0], tnode2, PersistenceFacade.getInstance().createModelReference("r:00000000-0000-4000-0000-011c89590288(jetbrains.mps.lang.core.structure)"), PersistenceFacade.getInstance().createNodeId("1082983041843")));
      TemplateContext context2 = context1.subContext();
      {
        Collection<SNode> tlist3 = null;
        final Iterable<SNode> copyListInput3 = QueriesGenerated.sourceNodesQuery_5_0(new SourceSubstituteMacroNodesContext(context2, copySrcListMacro_2hqiun_b0a0a1a4a3a4));
        tlist3 = environment.copyNodes(copyListInput3, copySrcListMacro_2hqiun_b0a0a1a4a3a4, "tpl/r:858292f3-d079-42c7-a340-20af00941ea2/5333329965167315376", context2);
        for (SNode child4 : TemplateUtil.asNotNull(tlist3)) {
          tnode2.addChild(myAggregationLinks[0], child4);
        }
        // TODO validate child 
      }
    } finally {
    }
    tlist1 = TemplateUtil.singletonList(tnode2);
    environment.registerLabel(context.getInput(), tnode2, "enum");
    return tlist1;
  }

  public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
    return apply(context.getEnvironment(), context);
  }

  @Override
  protected SConcept[] initConcepts() {
    SConcept[] rv = new SConcept[1];
    rv[0] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, "jetbrains.mps.lang.structure"), 0xfc26875dfbL, "EnumerationDataTypeDeclaration");
    return rv;
  }
  @Override
  protected SProperty[] initProperties() {
    SProperty[] rv = new SProperty[1];
    rv[0] = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    return rv;
  }
  @Override
  protected SReferenceLink[] initAssociationLinks() {
    SReferenceLink[] rv = new SReferenceLink[1];
    rv[0] = MetaAdapterFactory.getReferenceLink(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xfc26875dfbL, 0xfc3210ef05L, "memberDataType");
    return rv;
  }
  @Override
  protected SContainmentLink[] initAggregationLinks() {
    SContainmentLink[] rv = new SContainmentLink[1];
    rv[0] = MetaAdapterFactory.getContainmentLink(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xfc26875dfbL, 0xfc32151efeL, "member");
    return rv;
  }
  private static SNodePointer template_2hqiun_a0a3 = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167315375");
  private static SNodePointer propertyMacro_2hqiun_c0a0c0b0d0e = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167387965");
  private static SNodePointer copySrcListMacro_2hqiun_b0a0a1a4a3a4 = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167389348");
}
