package languagelab.lang.structure.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.TemplateDeclarationBase;
import jetbrains.mps.generator.runtime.TemplateDeclaration;
import org.jetbrains.mps.openapi.model.SNodeReference;
import java.util.Collection;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.GenerationException;
import org.jetbrains.mps.openapi.model.SNodeAccessUtil;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.generator.impl.reference.RefResolver;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.smodel.SReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

@Generated
public class Template_llmap_Type extends TemplateDeclarationBase implements TemplateDeclaration {

  public Template_llmap_Type() {
  }

  public SNodeReference getTemplateNode() {
    return template_ke713l_a0a3;
  }
  public Collection<SNode> apply(@NotNull final TemplateExecutionEnvironment environment, @NotNull final TemplateContext context) throws GenerationException {
    final SNode tnode1 = environment.createOutputNode(myConcepts[0]);
    try {
      environment.nodeCopied(context, tnode1, "tpl/r:858292f3-d079-42c7-a340-20af00941ea2/5333329965167315379");
      SNodeAccessUtil.setProperty(tnode1, myProperties[0], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetValue_6_0(new PropertyMacroContext(context, null, propertyMacro_ke713l_c0a0c0b0b0e))));
      SNodeAccessUtil.setProperty(tnode1, myProperties[1], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetValue_6_1(new PropertyMacroContext(context, "5333329965167315379", propertyMacro_ke713l_c0a0c0c0b0e))));
      SNodeAccessUtil.setProperty(tnode1, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetValue_6_2(new PropertyMacroContext(context, "eae03908-2235-4bea-9cd8-881b4e0cb934", propertyMacro_ke713l_c0a0c0d0b0e))));
      SNodeAccessUtil.setProperty(tnode1, myProperties[3], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetValue_6_3(new PropertyMacroContext(context, "llmap_Type", propertyMacro_ke713l_c0a0c0e0b0e))));
      environment.resolve(new RefResolver(tnode1, myAssociationLinks[0], context, new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167326006"), "BaseConcept") {
        @Override
        public Object resolve() {
          return QueriesGenerated.referenceMacro_GetReferent_6_0(createQueryContext());
        }
      });
      environment.resolve(new RefResolver(tnode1, myAssociationLinks[1], context, new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167373179"), "BaseConcept") {
        @Override
        public Object resolve() {
          return QueriesGenerated.referenceMacro_GetReferent_6_1(createQueryContext());
        }
      });
      TemplateContext context1 = context.subContext();
      {
        Collection<SNode> tlist2 = null;
        if (QueriesGenerated.ifMacro_Condition_6_0(new IfMacroContext(context1, ifMacroRef_ke713l_b0a0b0i0b0e))) {
          final SNode tnode3 = environment.createOutputNode(myConcepts[1]);
          try {
            tnode3.setReference(myAssociationLinks[2], SReference.create(myAssociationLinks[2], tnode3, PersistenceFacade.getInstance().createModelReference("r:862bdb7b-f55f-49a6-bc53-62cd4f9465cc(languagelab.lang.structure.structure)"), PersistenceFacade.getInstance().createNodeId("8677858327698377499")));
          } finally {
          }
          tlist2 = TemplateUtil.singletonList(tnode3);
        }
        for (SNode child4 : TemplateUtil.asNotNull(tlist2)) {
          tnode1.addChild(myAggregationLinks[0], child4);
        }
        // TODO validate child 
      }
      {
        Collection<SNode> tlist5 = null;
        if (QueriesGenerated.ifMacro_Condition_6_1(new IfMacroContext(context1, ifMacroRef_ke713l_b0a0b0j0b0e))) {
          final SNode tnode6 = environment.createOutputNode(myConcepts[1]);
          try {
            tnode6.setReference(myAssociationLinks[2], SReference.create(myAssociationLinks[2], tnode6, PersistenceFacade.getInstance().createModelReference("r:862bdb7b-f55f-49a6-bc53-62cd4f9465cc(languagelab.lang.structure.structure)"), PersistenceFacade.getInstance().createNodeId("5215824001461839993")));
          } finally {
          }
          tlist5 = TemplateUtil.singletonList(tnode6);
        }
        for (SNode child7 : TemplateUtil.asNotNull(tlist5)) {
          tnode1.addChild(myAggregationLinks[0], child7);
        }
        // TODO validate child 
      }
      {
        final SNode tnode8 = environment.createOutputNode(myConcepts[1]);
        try {
          tnode8.setReference(myAssociationLinks[2], SReference.create(myAssociationLinks[2], tnode8, PersistenceFacade.getInstance().createModelReference("r:fa713d69-08ea-4732-b1f2-cb07f9e103ef(jetbrains.mps.execution.util.structure)"), PersistenceFacade.getInstance().createNodeId("4666195181811081429")));
        } finally {
        }
        tnode1.addChild(myAggregationLinks[0], tnode8);
        // TODO validate child 
      }
      {
        Collection<SNode> tlist9 = null;
        final Iterable<SNode> copyListInput9 = QueriesGenerated.sourceNodesQuery_6_0(new SourceSubstituteMacroNodesContext(context1, copySrcListMacro_ke713l_b0a0a1a11a1a4));
        tlist9 = environment.copyNodes(copyListInput9, copySrcListMacro_ke713l_b0a0a1a11a1a4, "tpl/r:858292f3-d079-42c7-a340-20af00941ea2/9081158997091974991", context1);
        for (SNode child10 : TemplateUtil.asNotNull(tlist9)) {
          tnode1.addChild(myAggregationLinks[1], child10);
        }
        // TODO validate child 
      }
      {
        Collection<SNode> tlist11 = null;
        final Iterable<SNode> copyListInput11 = QueriesGenerated.sourceNodesQuery_6_1(new SourceSubstituteMacroNodesContext(context1, copySrcListMacro_ke713l_b0a0a1a21a1a4));
        tlist11 = environment.copyNodes(copyListInput11, copySrcListMacro_ke713l_b0a0a1a21a1a4, "tpl/r:858292f3-d079-42c7-a340-20af00941ea2/9081158997092040686", context1);
        for (SNode child12 : TemplateUtil.asNotNull(tlist11)) {
          tnode1.addChild(myAggregationLinks[1], child12);
        }
        // TODO validate child 
      }
      {
        Collection<SNode> tlist13 = null;
        final Iterable<SNode> copyListInput13 = QueriesGenerated.sourceNodesQuery_6_2(new SourceSubstituteMacroNodesContext(context1, copySrcListMacro_ke713l_b0a0a1a31a1a4));
        tlist13 = environment.copyNodes(copyListInput13, copySrcListMacro_ke713l_b0a0a1a31a1a4, "tpl/r:858292f3-d079-42c7-a340-20af00941ea2/9081158997092106356", context1);
        for (SNode child14 : TemplateUtil.asNotNull(tlist13)) {
          tnode1.addChild(myAggregationLinks[2], child14);
        }
        // TODO validate child 
      }
    } finally {
    }
    return TemplateUtil.singletonList(tnode1);
  }

  public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
    return apply(context.getEnvironment(), context);
  }

  @Override
  protected SConcept[] initConcepts() {
    SConcept[] rv = new SConcept[2];
    rv[0] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, "jetbrains.mps.lang.structure"), 0xf979ba0450L, "ConceptDeclaration");
    rv[1] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, "jetbrains.mps.lang.structure"), 0x110356fc618L, "InterfaceConceptReference");
    return rv;
  }
  @Override
  protected SProperty[] initProperties() {
    SProperty[] rv = new SProperty[4];
    rv[0] = MetaAdapterFactory.getProperty(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xf979ba0450L, 0xff49c1d648L, "rootable");
    rv[1] = MetaAdapterFactory.getProperty(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x1103553c5ffL, 0x5d2e6079771f8cc0L, "conceptId");
    rv[2] = MetaAdapterFactory.getProperty(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x1103553c5ffL, 0x7cf94884f2237423L, "languageId");
    rv[3] = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    return rv;
  }
  @Override
  protected SReferenceLink[] initAssociationLinks() {
    SReferenceLink[] rv = new SReferenceLink[3];
    rv[0] = MetaAdapterFactory.getReferenceLink(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xf979ba0450L, 0xf979be93cfL, "extends");
    rv[1] = MetaAdapterFactory.getReferenceLink(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x1103553c5ffL, 0x45b8a887cfd27b2cL, "sourceNode");
    rv[2] = MetaAdapterFactory.getReferenceLink(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x110356fc618L, 0x110356fe029L, "intfc");
    return rv;
  }
  @Override
  protected SContainmentLink[] initAggregationLinks() {
    SContainmentLink[] rv = new SContainmentLink[3];
    rv[0] = MetaAdapterFactory.getContainmentLink(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xf979ba0450L, 0x110358d693eL, "implements");
    rv[1] = MetaAdapterFactory.getContainmentLink(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x1103553c5ffL, 0xf979c3ba6bL, "linkDeclaration");
    rv[2] = MetaAdapterFactory.getContainmentLink(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x1103553c5ffL, 0xf979c3ba6cL, "propertyDeclaration");
    return rv;
  }
  private static SNodePointer template_ke713l_a0a3 = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167315379");
  private static SNodePointer propertyMacro_ke713l_c0a0c0b0b0e = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167327988");
  private static SNodePointer propertyMacro_ke713l_c0a0c0c0b0e = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167329838");
  private static SNodePointer propertyMacro_ke713l_c0a0c0d0b0e = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5333329965167368063");
  private static SNodePointer propertyMacro_ke713l_c0a0c0e0b0e = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "2840903799353012489");
  private static SNodePointer ifMacroRef_ke713l_b0a0b0i0b0e = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "9081158997092176006");
  private static SNodePointer ifMacroRef_ke713l_b0a0b0j0b0e = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "5215824001459050829");
  private static SNodePointer copySrcListMacro_ke713l_b0a0a1a11a1a4 = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "9081158997092038276");
  private static SNodePointer copySrcListMacro_ke713l_b0a0a1a21a1a4 = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "9081158997092104296");
  private static SNodePointer copySrcListMacro_ke713l_b0a0a1a31a1a4 = new SNodePointer("r:858292f3-d079-42c7-a340-20af00941ea2(languagelab.lang.structure.generator.template.main@generator)", "9081158997092169640");
}
