package languagelab.lang.textual.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new TextAggregate_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new TextAttribute_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new TextConstant_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new TextReference_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new TextSyntax_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb6fL), MetaIdFactory.conceptId(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb71L), MetaIdFactory.conceptId(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb73L), MetaIdFactory.conceptId(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x4fd0d3e12aafcb6cL), MetaIdFactory.conceptId(0x884830c7aa44151L, 0xa40f0c18ee248daaL, 0x6d0f56d69c3c1cbaL)).seal();
}
