package languagelab.lang.smodel.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ChildRef = 0;
  public static final int PropertyRef = 1;
  public static final int ReferenceRef = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x1111b0d61b274daaL, 0x92f98b9e03529a60L);
    builder.put(0x4f31c8d37d2477eeL, ChildRef);
    builder.put(0x4fdf930a19049c8fL, PropertyRef);
    builder.put(0x4f31c8d37d2477ebL, ReferenceRef);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
