package languagelab.lang.smodel.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptChildRef = createDescriptorForChildRef();
  /*package*/ final ConceptDescriptor myConceptPropertyRef = createDescriptorForPropertyRef();
  /*package*/ final ConceptDescriptor myConceptReferenceRef = createDescriptorForReferenceRef();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptChildRef, myConceptPropertyRef, myConceptReferenceRef);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ChildRef:
        return myConceptChildRef;
      case LanguageConceptSwitch.PropertyRef:
        return myConceptPropertyRef;
      case LanguageConceptSwitch.ReferenceRef:
        return myConceptReferenceRef;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForChildRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.lang.smodel", "ChildRef", 0x1111b0d61b274daaL, 0x92f98b9e03529a60L, 0x4f31c8d37d2477eeL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.baseLanguage.structure.Expression", 0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:3bfc6dac-fd84-4312-99cc-a9f470983c7e(languagelab.lang.smodel.structure)/5706563013518325742");
    b.version(2);
    b.associate("typeDecl", 0x4f31c8d37d2477efL).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("5706563013518325743").done();
    b.associate("chldDecl", 0x4f31c8d37d2477f0L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("5706563013518325744").done();
    b.alias("child//");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPropertyRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.lang.smodel", "PropertyRef", 0x1111b0d61b274daaL, 0x92f98b9e03529a60L, 0x4fdf930a19049c8fL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.baseLanguage.structure.Expression", 0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:3bfc6dac-fd84-4312-99cc-a9f470983c7e(languagelab.lang.smodel.structure)/5755480520381471887");
    b.version(2);
    b.associate("typeDecl", 0x4fdf930a19049c90L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("5755480520381471888").done();
    b.associate("propDecl", 0x4fdf930a1904cf07L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("5755480520381484807").done();
    b.alias("property//");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReferenceRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.lang.smodel", "ReferenceRef", 0x1111b0d61b274daaL, 0x92f98b9e03529a60L, 0x4f31c8d37d2477ebL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.baseLanguage.structure.Expression", 0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:3bfc6dac-fd84-4312-99cc-a9f470983c7e(languagelab.lang.smodel.structure)/5706563013518325739");
    b.version(2);
    b.associate("typeDecl", 0x4f31c8d37d2477ecL).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("5706563013518325740").done();
    b.associate("refeDecl", 0x4f31c8d37d2477edL).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("5706563013518325741").done();
    b.alias("reference//");
    return b.create();
  }
}
