package languagelab.lang.structure.utils;

/*Generated by MPS */

import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class SStuffHelper {
  public static SProperty ATTRIBUTE_TYPE = MetaAdapterFactory.getProperty(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1978f03659121e6L, 0x1978f03659121eaL, "e");
  public static SProperty TYPE_ISNAMED = MetaAdapterFactory.getProperty(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, 0x1d49f38c290821baL, "isNamed");

  public static SReferenceLink ATTRIBUTE_ENUMTYPE = MetaAdapterFactory.getReferenceLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1978f03659121e6L, 0x1678091ddc706f43L, "enumType");
  public static SReferenceLink TYPE_PARENTTYPE = MetaAdapterFactory.getReferenceLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, 0x55ce2ad3d281e42bL, "parentType");
  public static SReferenceLink REFERENCE_TYPE = MetaAdapterFactory.getReferenceLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1978f03659088ddL, 0x1978f03659088f7L, "type");
  public static SReferenceLink AGGREGATE_TYPE = MetaAdapterFactory.getReferenceLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x1d49f38c2913f9d3L, 0x1d49f38c29140d0dL, "type");

  public static SContainmentLink TYPE_ATTRIBUTES = MetaAdapterFactory.getContainmentLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, 0x1978f0365912249L, "attributes");
  public static SContainmentLink TYPE_REFERENCES = MetaAdapterFactory.getContainmentLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, 0x1978f03659088e1L, "references");
  public static SContainmentLink TYPE_AGGREGATES = MetaAdapterFactory.getContainmentLink(0x2ef2eb400107434eL, 0xb65d407af430cfecL, 0x6d0f56d69c3c1cbaL, 0x1d49f38c291302ceL, "aggregates");
}
