package languagelab.mps.lang.adaptedGenerator.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.ConceptKind;
import jetbrains.mps.smodel.runtime.StaticScope;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptLLChangeIfMacro = createDescriptorForLLChangeIfMacro();
  /*package*/ final ConceptDescriptor myConceptLLCopySourceListMacro = createDescriptorForLLCopySourceListMacro();
  /*package*/ final ConceptDescriptor myConceptLLIfMacro = createDescriptorForLLIfMacro();
  /*package*/ final ConceptDescriptor myConceptLLLoopMacro = createDescriptorForLLLoopMacro();
  /*package*/ final ConceptDescriptor myConceptLLParentReferenceMacro = createDescriptorForLLParentReferenceMacro();
  /*package*/ final ConceptDescriptor myConceptLLPropertyMacro = createDescriptorForLLPropertyMacro();
  /*package*/ final ConceptDescriptor myConceptLLPropertyMacro_GetPropertyValue_Behaviour = createDescriptorForLLPropertyMacro_GetPropertyValue_Behaviour();
  /*package*/ final ConceptDescriptor myConceptLLReduction_MappingRule = createDescriptorForLLReduction_MappingRule();
  /*package*/ final ConceptDescriptor myConceptLLRootTemplateAnnotation = createDescriptorForLLRootTemplateAnnotation();
  /*package*/ final ConceptDescriptor myConceptLLRoot_MappingRule = createDescriptorForLLRoot_MappingRule();
  /*package*/ final ConceptDescriptor myConceptLLSelfReferenceMacro = createDescriptorForLLSelfReferenceMacro();
  /*package*/ final ConceptDescriptor myConceptLLSimpleReferenceMacro = createDescriptorForLLSimpleReferenceMacro();
  /*package*/ final ConceptDescriptor myConceptLLSpecialReferenceMacro = createDescriptorForLLSpecialReferenceMacro();
  /*package*/ final ConceptDescriptor myConceptLLTemplateDeclaration = createDescriptorForLLTemplateDeclaration();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xb401a68083254110L, 0x8fd384331ff25befL, "jetbrains.mps.lang.generator");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptLLChangeIfMacro, myConceptLLCopySourceListMacro, myConceptLLIfMacro, myConceptLLLoopMacro, myConceptLLParentReferenceMacro, myConceptLLPropertyMacro, myConceptLLPropertyMacro_GetPropertyValue_Behaviour, myConceptLLReduction_MappingRule, myConceptLLRootTemplateAnnotation, myConceptLLRoot_MappingRule, myConceptLLSelfReferenceMacro, myConceptLLSimpleReferenceMacro, myConceptLLSpecialReferenceMacro, myConceptLLTemplateDeclaration);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.LLChangeIfMacro:
        return myConceptLLChangeIfMacro;
      case LanguageConceptSwitch.LLCopySourceListMacro:
        return myConceptLLCopySourceListMacro;
      case LanguageConceptSwitch.LLIfMacro:
        return myConceptLLIfMacro;
      case LanguageConceptSwitch.LLLoopMacro:
        return myConceptLLLoopMacro;
      case LanguageConceptSwitch.LLParentReferenceMacro:
        return myConceptLLParentReferenceMacro;
      case LanguageConceptSwitch.LLPropertyMacro:
        return myConceptLLPropertyMacro;
      case LanguageConceptSwitch.LLPropertyMacro_GetPropertyValue_Behaviour:
        return myConceptLLPropertyMacro_GetPropertyValue_Behaviour;
      case LanguageConceptSwitch.LLReduction_MappingRule:
        return myConceptLLReduction_MappingRule;
      case LanguageConceptSwitch.LLRootTemplateAnnotation:
        return myConceptLLRootTemplateAnnotation;
      case LanguageConceptSwitch.LLRoot_MappingRule:
        return myConceptLLRoot_MappingRule;
      case LanguageConceptSwitch.LLSelfReferenceMacro:
        return myConceptLLSelfReferenceMacro;
      case LanguageConceptSwitch.LLSimpleReferenceMacro:
        return myConceptLLSimpleReferenceMacro;
      case LanguageConceptSwitch.LLSpecialReferenceMacro:
        return myConceptLLSpecialReferenceMacro;
      case LanguageConceptSwitch.LLTemplateDeclaration:
        return myConceptLLTemplateDeclaration;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForLLChangeIfMacro() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLChangeIfMacro", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d4b60b0L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.ReferenceMacro", 0xb401a68083254110L, 0x8fd384331ff25befL, 0xfd7f44d616L);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216630378672");
    b.version(2);
    b.property("dummy", 0x3afac1bd2d4b60b3L).type(PrimitiveTypeId.BOOLEAN).origin("4249922216630378675").done();
    b.associate("myRef", 0x3afac1bd2d4b60b1L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("4249922216630378673").done();
    b.kind(ConceptKind.IMPLEMENTATION, StaticScope.GLOBAL);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLCopySourceListMacro() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLCopySourceListMacro", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d504518L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.NodeMacro", 0xb401a68083254110L, 0x8fd384331ff25befL, 0xfd47ed6742L);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216630699288");
    b.version(2);
    b.associate("myAggregate", 0x3afac1bd2d50451aL).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("4249922216630699290").done();
    b.kind(ConceptKind.IMPLEMENTATION, StaticScope.GLOBAL);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLIfMacro() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLIfMacro", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d525942L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.NodeMacro", 0xb401a68083254110L, 0x8fd384331ff25befL, 0xfd47ed6742L);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216630835522");
    b.version(2);
    b.property("dummy", 0x3afac1bd2d525945L).type(PrimitiveTypeId.BOOLEAN).origin("4249922216630835525").done();
    b.associate("checkProperty", 0x3afac1bd2d525943L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("4249922216630835523").done();
    b.kind(ConceptKind.IMPLEMENTATION, StaticScope.GLOBAL);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLLoopMacro() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLLoopMacro", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d590475L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.NodeMacro", 0xb401a68083254110L, 0x8fd384331ff25befL, 0xfd47ed6742L);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216631272565");
    b.version(2);
    b.associate("loopElements", 0x3afac1bd2d590476L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("4249922216631272566").done();
    b.kind(ConceptKind.IMPLEMENTATION, StaticScope.GLOBAL);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLParentReferenceMacro() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLParentReferenceMacro", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d5904aaL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.ReferenceMacro", 0xb401a68083254110L, 0x8fd384331ff25befL, 0xfd7f44d616L);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216631272618");
    b.version(2);
    b.kind(ConceptKind.IMPLEMENTATION, StaticScope.GLOBAL);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLPropertyMacro() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLPropertyMacro", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d5b525eL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.PropertyMacro", 0xb401a68083254110L, 0x8fd384331ff25befL, 0xfd47e9f6f0L);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216631423582");
    b.version(2);
    b.associate("myAttr", 0x3afac1bd2d5b5261L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("4249922216631423585").done();
    b.kind(ConceptKind.IMPLEMENTATION, StaticScope.GLOBAL);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLPropertyMacro_GetPropertyValue_Behaviour() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLPropertyMacro_GetPropertyValue_Behaviour", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d5904c5L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.PropertyMacro_GetPropertyValue", 0xb401a68083254110L, 0x8fd384331ff25befL, 0x10fe3afb5ffL);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216631272645");
    b.version(2);
    b.kind(ConceptKind.INTERFACE, StaticScope.GLOBAL);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLReduction_MappingRule() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLReduction_MappingRule", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d54831eL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.Reduction_MappingRule", 0xb401a68083254110L, 0x8fd384331ff25befL, 0x10fca296532L);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216630977310");
    b.version(2);
    b.associate("forType", 0x3afac1bd2d54831fL).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("4249922216630977311").done();
    b.kind(ConceptKind.IMPLEMENTATION, StaticScope.GLOBAL);
    b.alias("LLmap");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLRootTemplateAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLRootTemplateAnnotation", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d5b529aL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.RootTemplateAnnotation", 0xb401a68083254110L, 0x8fd384331ff25befL, 0x11017244494L);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216631423642");
    b.version(2);
    b.associate("forType", 0x3afac1bd2d5b529bL).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("4249922216631423643").done();
    b.kind(ConceptKind.IMPLEMENTATION, StaticScope.GLOBAL);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLRoot_MappingRule() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLRoot_MappingRule", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d56c529L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.Root_MappingRule", 0xb401a68083254110L, 0x8fd384331ff25befL, 0x10fd54746dbL);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216631125289");
    b.version(2);
    b.associate("forType", 0x3afac1bd2d56c52aL).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("4249922216631125290").done();
    b.kind(ConceptKind.IMPLEMENTATION, StaticScope.GLOBAL);
    b.alias("LLmap");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLSelfReferenceMacro() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLSelfReferenceMacro", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d5b52f5L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.ReferenceMacro", 0xb401a68083254110L, 0x8fd384331ff25befL, 0xfd7f44d616L);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216631423733");
    b.version(2);
    b.kind(ConceptKind.IMPLEMENTATION, StaticScope.GLOBAL);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLSimpleReferenceMacro() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLSimpleReferenceMacro", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d5b5310L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.ReferenceMacro", 0xb401a68083254110L, 0x8fd384331ff25befL, 0xfd7f44d616L);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216631423760");
    b.version(2);
    b.associate("myRef", 0x3afac1bd2d5b5313L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("4249922216631423763").done();
    b.kind(ConceptKind.IMPLEMENTATION, StaticScope.GLOBAL);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLSpecialReferenceMacro() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLSpecialReferenceMacro", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d5b534cL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.generator.structure.ReferenceMacro", 0xb401a68083254110L, 0x8fd384331ff25befL, 0xfd7f44d616L);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216631423820");
    b.version(2);
    b.associate("myRef", 0x3afac1bd2d5b534fL).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(true).origin("4249922216631423823").done();
    b.kind(ConceptKind.IMPLEMENTATION, StaticScope.GLOBAL);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLLTemplateDeclaration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.lang.adaptedGenerator", "LLTemplateDeclaration", 0xe0a091b2dc994294L, 0xa6268d2e85598ee6L, 0x3afac1bd2d58fca2L);
    b.class_(false, false, true);
    b.super_("jetbrains.mps.lang.generator.structure.TemplateDeclaration", 0xb401a68083254110L, 0x8fd384331ff25befL, 0xfe43cb41d0L);
    b.origin("r:f94f7eaf-9b72-4a95-af4b-b4ca35e600f1(languagelab.mps.lang.adaptedGenerator.structure)/4249922216631270562");
    b.version(2);
    b.associate("forType", 0x3afac1bd2d58fca3L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("4249922216631270563").done();
    b.kind(ConceptKind.INTERFACE, StaticScope.GLOBAL);
    b.alias("ll template declaration");
    return b.create();
  }
}
